version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./dbscripts/craft.initial.sql:/docker-entrypoint-initdb.d/craft.initial.sql
  law_scraper:
    build: .
    volumes:
      - .:/usr/src/law-scraper
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
    env_file:
      - .env
    container_name: law-scraper